export default {
    productsInHomePage: '.fixed_wrapper',
    addToCart: '.cart',
    inShoppingCart: 'td',
    checkout: '#cart_checkout1',
    continueBtn: '#accountFrm > fieldset > .btn',
    firstName: '#AccountFrm_firstname',
    lastName: '#AccountFrm_lastname',
    email: '#AccountFrm_email',
    phone: '#AccountFrm_telephone',
    fax: '#AccountFrm_fax',
    company: '#AccountFrm_company',
    address_1: '#AccountFrm_address_1',
    city: '#AccountFrm_city',
    regionList: '#AccountFrm_zone_id',
    postcode: '#AccountFrm_postcode',
    countryList: '#AccountFrm_country_id',
    loginName: '#AccountFrm_loginname',
    password: '#AccountFrm_password',
    passwordConfirm: '#AccountFrm_confirm',
    noNewsletter: '#AccountFrm_newsletter0',
    agreePrivacyPolicy: '#AccountFrm_agree',
    continueBtnCreateAccoun: '.col-md-2 > .btn',
    checkoutBtn: '#checkout_btn',
    continueProcessBtn: '.mb40 > .btn'
};